import os

PORT = 9000
DEBUG = True
TESTING = False

assert "KADI_APPS_CONFIG_DIR" in os.environ, "KADI_APPS_CONFIG_DIR is not in environment"

KADI_APPS_CONFIG_DIR = os.environ["KADI_APPS_CONFIG_DIR"]
LOG_LEVEL = 'INFO'
TOKEN_VERSION = (1, 0)

SEND_FILE_MAX_AGE_DEFAULT = 5
